redis:
  # NOTE: leave ${VERSION_TAG} as is - it is used exclusively by the Jenkins build pipeline
  image: ${IMAGE_TAG}
  ports:
    - "6379:6379"
  volumes:
    - /data/redis:/var/lib/redis
  restart: always
