redis:
  # NOTE: - leave ${IMAGE_TAG} as is - it is used exclusively by the Jenkins build pipeline
  image: ${IMAGE_TAG}
  ports:
    - "6379:6379"
  volumes:
    - /data/redis:/var/lib/redis
  restart: always


# ANOTHER EXAMPLE:

# version: '3'
#
# services:
#    db:
#      image: ${IMAGE_TAG} <== if this app repo was a mysql build for a wordpress frontend
#      volumes:
#        - db_data:/var/lib/mysql
#      restart: always
#
#    wordpress:
#      depends_on:
#        - db
#      image: wordpress:latest
#      ports:
#        - "8000:80"
#      restart: always
#      environment:
#        WORDPRESS_DB_HOST: db:3306
#        WORDPRESS_DB_USER: wordpress
#        WORDPRESS_DB_PASSWORD: wordpress
# volumes:
#     db_data:
